# Generated by Django 3.2.5 on 2021-08-29 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='findtutorpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('main_content', models.TextField(max_length=200)),
                ('subject', models.CharField(max_length=30)),
                ('calendar', models.CharField(max_length=30)),
                ('salary', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('date_outdate', models.PositiveSmallIntegerField(default=15)),
                ('post_img1', models.ImageField(blank=True, null=True, upload_to='postImg', verbose_name='Ảnh 1:')),
                ('post_img2', models.ImageField(blank=True, null=True, upload_to='postImg', verbose_name='Ảnh 2:')),
                ('post_img3', models.ImageField(blank=True, null=True, upload_to='postImg', verbose_name='Ảnh 3:')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('report', models.ManyToManyField(blank=True, default=None, related_name='report_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
