# Generated by Django 3.2.5 on 2021-08-30 21:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutor', '0002_subs_fintutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subs_fintutor',
            name='list_user',
        ),
        migrations.AddField(
            model_name='subs_fintutor',
            name='list_user',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
