# Generated by Django 3.2.5 on 2021-09-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_auto_20210830_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findtutorpost',
            name='post_img1',
            field=models.ImageField(blank=True, null=True, upload_to='postImg/tutor/', verbose_name='Ảnh 1:'),
        ),
        migrations.AlterField(
            model_name='findtutorpost',
            name='post_img2',
            field=models.ImageField(blank=True, null=True, upload_to='postImg/tutor/', verbose_name='Ảnh 2:'),
        ),
        migrations.AlterField(
            model_name='findtutorpost',
            name='post_img3',
            field=models.ImageField(blank=True, null=True, upload_to='postImg/tutor/', verbose_name='Ảnh 3:'),
        ),
    ]
