# Generated by Django 3.2.5 on 2021-09-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_auto_20210901_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='findtutorpost',
            name='post_img1',
            field=models.ImageField(blank=True, null=True, upload_to='postImg/tutor/', verbose_name='Img 1:'),
        ),
        migrations.AlterField(
            model_name='findtutorpost',
            name='post_img2',
            field=models.ImageField(blank=True, null=True, upload_to='postImg/tutor/', verbose_name='Img 2:'),
        ),
        migrations.AlterField(
            model_name='findtutorpost',
            name='post_img3',
            field=models.ImageField(blank=True, null=True, upload_to='postImg/tutor/', verbose_name='Img 3:'),
        ),
    ]
