# Generated by Django 3.2.5 on 2021-07-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='years_of_birth',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Năm sinh'),
        ),
    ]
