# Generated by Django 3.2.5 on 2021-07-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='more',
            field=models.TextField(blank=True, verbose_name='Giới thiệu bản thân (optional):'),
        ),
    ]
