# Generated by Django 3.2.5 on 2021-07-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_user_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='more',
            field=models.TextField(blank=True, verbose_name='More:'),
        ),
    ]
