# Generated by Django 3.2.5 on 2021-07-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default4654654#%@#%@#%.png', upload_to='avatar', verbose_name='Avatar:'),
        ),
    ]
