# Generated by Django 3.2.5 on 2021-08-24 17:08

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': '<small style="color:#e60000">Tên đăng nhập đã tồn tại.</small>'}, help_text='<small style="color:teal">Không quá 30 ký tự. Chỉ có thể bao gồm chữ cái, số và các ký tự @ . + - _</small>', max_length=30, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Tên đăng nhập:'),
        ),
    ]
