# Generated by Django 3.2.5 on 2021-08-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20210828_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
