# Generated by Django 3.2.5 on 2021-08-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_user_paid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sub_findtutor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
