# Generated by Django 3.2.5 on 2021-09-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_user_is_sub_findtutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sub_employee',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_sub_homework',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_sub_market',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
