# Generated by Django 3.2.5 on 2021-09-13 16:26

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20210910_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Address:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=150, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Fullname :'),
        ),
        migrations.AlterField(
            model_name='user',
            name='more',
            field=models.TextField(blank=True, verbose_name='More:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, max_length=500, verbose_name='School:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sexs',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=6, verbose_name='Sexs:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialize',
            field=models.CharField(max_length=500, verbose_name='Special:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': '<small style="color:#e60000">Username is already existed.</small>'}, help_text='<small style="color:teal">Maximun is 30 characters. include number, characters and @ . + - _</small>', max_length=30, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Username:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='yearofschool',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Years of school:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='years_of_birth',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Years old'),
        ),
    ]
