# Generated by Django 3.2.5 on 2021-07-31 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_stt', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
